### ISSUE TITLE
PageNotFoundException

### ISSUE THREAD

**Issue by Lukas2019** [EjazAmir/newsfeed_multiple_imageview#1]
When I try to open my images with newsfeed_multiple_imageview I get the following error:
PageNotFoundException: Cannot retrieve length of file, path="http://02064-54968.pph-server.de/files/e1464018-0ec1-4f9c-a7a6-2138b66cd7d7/fee2fc3f-634c-42ae-ba24-cbf9eac7029e.jpeg" (OS Error: No suchfiel or directory, errno=2)

![errorlage](https://github.com/user-attachments/assets/11f9847a-973c-4f0a-8cf0-c7235e8b78ab)
![errordetail](https://github.com/user-attachments/assets/63076de4-0aba-4299-8fec-cb4caacf3dab)

My code:
`
NewsfeedMultipleImageView(
            imageUrls: ["http://02064-54968.pph-server.de/files/e1464018-0ec1-4f9c-a7a6-2138b66cd7d7/fee2fc3f-634c-42ae-ba24-cbf9eac7029e.jpeg"],
            marginLeft: 10.0,
            marginRight: 10.0,
            marginBottom: 10.0,
            marginTop: 10.0,
          );
`

**Comment by dhruvanbhalara** [comment]
Hi @Lukas2019,
you can use fork repo until PR gets merged

```yaml
  newsfeed_multiple_imageview:
    git:
      url: https://github.com/dhruvanbhalara/newsfeed_multiple_imageview
      ref: development
```
